### ISSUE TITLE
Update for Godot 3.1?

### ISSUE THREAD

**Issue by JDSECO** [AlexHolly/godot-rest-server#1]
I tried your code, but in Godot 3.1, there's an error. It's this.
Invalid call to function 'is_connected' in base 'StreamPeerTCP'. Expected 3 arguments.

I suspect this error is due to changes in Godot.

**Comment by AlexHolly** [comment]
I didn't use this for quite some time, I fixed a few things, the GET request seems to work I hope the others do too.
